# Generated by Django 3.2.8 on 2021-10-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Carrera',
            new_name='carrera',
        ),
    ]
